// IL MAZZO — non aprire questo file se vuoi giocare senza sapere le domande.
//
// Ogni coppia: [domanda A, domanda B, unità, difficoltà, "+" se piccante]
//   unità:  "n" numero libero · "%" da 0 a 100 · "10" da 1 a 10
//   difficoltà per l'impostore: 1 le due domande si somigliano, facile mimetizzarsi
//                               2 intervalli simili ma temi diversi
//                               3 difficile da difendere, o domande quasi opposte
//   "+" alcol, baci ed ex, scommesse, chat private: chi crea la stanza può
//       toglierle per la sessione (partite con bambini)
// Quale delle due è la «vera» lo decide il sorteggio a ogni round.
// {G} diventa il nome di un giocatore della stanza.

var MAZZO = [

// ---------------------------------------------------------------- CONTEGGI
["Quanti cugini hai?", "Quanti ex compagni di classe senti ancora?", "n", 2],
["Quante paia di scarpe hai?", "Quante giacche e cappotti hai nell'armadio?", "n", 2],
["Quanti caffè bevi in una giornata normale?", "Quante volte al giorno controlli che ore sono?", "n", 3],
["Quanti libri hai letto nell'ultimo anno?", "Quanti film hai visto al cinema nell'ultimo anno?", "n", 1],
["Quante volte sei finito al pronto soccorso in vita tua?", "Quante multe hai preso in vita tua?", "n", 1],
["A che età hai dato il primo bacio?", "A che età hai guidato per la prima volta?", "n", 2, "+"],
["Quante app hai sulla prima schermata del telefono?", "Quanti gruppi WhatsApp hai silenziato?", "n", 2],
["Quanti messaggi non letti hai adesso sul telefono?", "Quante foto hai scattato nell'ultima settimana?", "n", 2],
["Quante ore passi al telefono in un giorno?", "Quante ore passi seduto in un giorno?", "n", 2],
["Quanti concerti hai visto in vita tua?", "A quanti matrimoni sei stato?", "n", 1],
["Quante volte sei andato in palestra nell'ultimo mese?", "Quante volte hai ordinato cibo a domicilio nell'ultimo mese?", "n", 1],
["In quante lingue sai dire almeno «grazie»?", "Quanti piatti sai cucinare senza guardare la ricetta?", "n", 2],
["Quanti minuti ci metti a prepararti la mattina?", "Quanti minuti ci metti ad arrivare al lavoro o a scuola?", "n", 1],
["Quante sveglie metti la mattina?", "Quanti cuscini usi per dormire?", "n", 1],
["Quante volte hai cambiato numero di telefono?", "Quante ossa ti sei rotto in vita tua?", "n", 2],
["Quanti euro hai nel portafoglio adesso?", "Quanti euro hai speso l'ultima volta che sei uscito a cena?", "n", 2],
["Quanti euro spenderesti al massimo per un paio di scarpe?", "Quanti euro spenderesti al massimo per il biglietto di un concerto?", "n", 1],
["A che età hai smesso di credere a Babbo Natale?", "A che età hai avuto il tuo primo telefono?", "n", 2],
["Quante volte ti sei addormentato al cinema?", "Quante volte hai pianto guardando un film?", "n", 2],
["Quanti piani ha il palazzo in cui vivi?", "Quanti vicini di casa conosci per nome?", "n", 2],
["Quante piante hai in casa?", "Quante tazze hai in casa?", "n", 2],
["Quanti tatuaggi hai, o vorresti avere?", "Quanti orecchini o piercing hai, o vorresti avere?", "n", 1],
["Quante volte all'anno vai dal parrucchiere o dal barbiere?", "Quante volte all'anno vai dal dentista?", "n", 1],
["Quante password diverse usi davvero?", "Quante mail ricevi in un giorno?", "n", 3],
["Quante persone inviteresti alla tua festa di compleanno ideale?", "Quanti numeri hai in rubrica senza sapere di chi sono?", "n", 3],
["Quanti selfie hai nel rullino del telefono?", "Quanti screenshot hai nel rullino del telefono?", "n", 2],
["Quanti chilometri riusciresti a correre senza fermarti?", "Quanti piani di scale fai senza fiatone?", "n", 2],
["Fino a che età vorresti vivere?", "A che età vorresti andare in pensione?", "n", 3],
["A che età hai avuto la prima cotta?", "A che età hai imparato ad andare in bici?", "n", 1],
["Quante volte hai visto il tuo film preferito?", "Quante volte sei stato nella tua città preferita?", "n", 2],
["Con quanti gradi esci in maniche corte?", "A quanti gradi metti il riscaldamento in casa?", "n", 2],
["Quanti bicchieri d'acqua bevi al giorno?", "Quante volte al giorno ti lavi le mani?", "n", 1],
["Quante serie tv hai iniziato e mai finito?", "Quanti libri hai iniziato e mai finito?", "n", 1],
["Quante volte sei stato rimandato o bocciato?", "Quante volte ti hanno mandato fuori dalla classe?", "n", 1],
["Quante volte hai perso le chiavi di casa?", "Quante volte hai dimenticato il compleanno di una persona importante?", "n", 1],
["Quanti euro hai speso per l'ultimo regalo che hai fatto?", "Quanti euro vale la cosa più costosa che hai addosso adesso?", "n", 2],
["Quante ore hai studiato per l'esame più difficile della tua vita?", "Quante ore di fila hai giocato a un videogioco, al massimo?", "n", 2],
["Quante volte ti sei tinto i capelli?", "Quante volte hai cambiato completamente taglio di capelli?", "n", 1],
["Quanti giorni al massimo sei stato senza telefono?", "Quanti giorni al massimo sei stato senza farti la doccia?", "n", 2],
["Quante volte al mese esci a cena fuori?", "Quante volte al mese chiami i tuoi genitori?", "n", 2],
["Quante bugie dici in una settimana, a occhio?", "Quante volte a settimana scrivi «sto arrivando» quando sei ancora a casa?", "n", 1],
["Quante canzoni sai cantare a memoria dall'inizio alla fine?", "Quanti numeri di telefono sai a memoria?", "n", 3],
["Per quanti anni hai fatto uno sport di squadra?", "Per quanti anni hai suonato uno strumento?", "n", 1],
["Quante volte hai rotto lo schermo del telefono?", "Quante volte ti è caduto il telefono in acqua?", "n", 2],
["Quanti ex puoi contare?", "Quante persone hai bloccato sui social?", "n", 2, "+"],
["Quante persone hai baciato in vita tua?", "Quante volte ti sei innamorato davvero?", "n", 2, "+"],
["Quante volte ti sei ubriacato nell'ultimo anno?", "Quante volte hai fatto l'alba nell'ultimo anno?", "n", 1, "+"],
["Quanti shottini reggi prima di stare male?", "Quante birre bevi in una serata normale?", "n", 1, "+"],
["Quante volte hai mentito sulla tua età?", "Quante volte hai finto di stare male per saltare scuola o lavoro?", "n", 2],
["A che età sei andato (o andrai) a vivere da solo?", "A che età vorresti avere il primo figlio?", "n", 2],
["Quante ore al giorno passi sui social?", "Quante ore a settimana fai sport?", "n", 2],
["Quanti minuti di ritardo sono accettabili a un appuntamento?", "Quanti minuti aspetti l'autobus prima di andare a piedi?", "n", 1],
["Quanti minuti ci metti a scegliere cosa guardare su Netflix?", "Quanti minuti ci metti a rispondere a un messaggio importante?", "n", 2],
["Quanti euro al mese spendi in abbonamenti?", "Quanti euro al mese spendi in caffè al bar?", "n", 1],
["Quanti regali di Natale fai ogni anno?", "Quante persone ti hanno fatto gli auguri all'ultimo compleanno?", "n", 3],
["Quante volte hai dormito in tenda?", "Quante volte hai dormito in macchina?", "n", 1],
["Quanti aerei hai preso nell'ultimo anno?", "Quanti treni hai perso in vita tua?", "n", 2],
["Quanti amici veri hai?", "Quanti gruppi WhatsApp attivi hai?", "n", 2],
["Da quanti anni hai il telefono che usi adesso?", "Da quanti anni hai lo stesso taglio di capelli?", "n", 2],
["Quante volte hai rifatto il letto questa settimana?", "Quante volte hai cucinato questa settimana?", "n", 1],
["Quanti euro pagheresti per sapere cosa pensano davvero di te?", "Per quanti euro ti raderesti i capelli a zero?", "n", 3],
["Per quanti euro mangeresti un insetto vivo?", "Per quanti euro staresti una settimana senza telefono?", "n", 2],
["Per quanti euro ti tatueresti il nome di qualcuno a questo tavolo?", "Per quanti euro ti raderesti le sopracciglia?", "n", 1],
["Quanti passi fai in un giorno, a occhio?", "Quante parole conosci in inglese, a occhio?", "n", 3],
["Quanti giorni è durata la vacanza più lunga che hai fatto?", "Quante ore è durato il viaggio più lungo che hai fatto?", "n", 2],
["Quanti giorni all'anno vai al mare?", "Quanti giorni all'anno passi a letto malato?", "n", 3],
["Quanti chilometri ci sono tra la casa dove sei cresciuto e quella dove vivi?", "Quanti chilometri hai fatto al massimo per una serata?", "n", 2],
["Quante volte ti hanno lasciato?", "Quante volte hai lasciato qualcuno?", "n", 1],
["Quanti messaggi hai mandato oggi?", "Quante notifiche hai ricevuto oggi?", "n", 1],
["Quanti anni ti senti dentro?", "A che età pensi di essere stato al massimo della forma?", "n", 2],
["A che età hai preso la prima sbronza?", "A che età hai fatto la prima vacanza senza genitori?", "n", 1, "+"],
["Quanti giochi da tavolo hai in casa?", "Quanti mazzi di carte hai in casa?", "n", 1],
["Quanti euro costava la bottiglia di vino più cara che hai bevuto?", "Quanti euro costava la cena più cara che hai pagato?", "n", 1],
["Quante volte hai visto l'alba apposta?", "Quante volte hai fatto il bagno in mare di notte?", "n", 1],
["Quanti selfie fai in una settimana?", "Quante storie pubblichi in una settimana?", "n", 1],
["Quante volte ti sei perso in una città nuova?", "Quante volte hai preso il treno o l'autobus sbagliato?", "n", 1],
["Quanti film horror hai visto in vita tua?", "Quanti film di Natale guardi ogni dicembre?", "n", 3],
["Quanti secondi riesci a stare in apnea?", "Quanti secondi reggi a guardare negli occhi uno sconosciuto?", "n", 3],
["Quanti gusti prendi di solito nel cono gelato?", "Quanti cucchiaini di zucchero metti nel caffè?", "n", 1],
["Quanti parenti vedi al pranzo di Natale?", "Quanti colleghi o compagni di corso saluti ogni giorno?", "n", 2],
["Quante volte hai cambiato idea su cosa fare da grande?", "Quante volte hai cambiato foto profilo nell'ultimo anno?", "n", 1],
["Quanti film hai visto più di tre volte?", "Quante canzoni hai ascoltato più di cento volte?", "n", 3],
["A che età hai imparato a nuotare?", "A che età sei andato al primo concerto?", "n", 2],
["Quante figuracce hai fatto davanti a qualcuno che ti piaceva?", "Quante volte hai mandato un messaggio alla persona sbagliata?", "n", 1],
["Quanti piatti sai cucinare davvero bene?", "Quante barzellette sai raccontare?", "n", 1],
["Quante volte alla settimana mangi pasta?", "Quante volte alla settimana mangi fuori casa?", "n", 1],
["Quanti euro hai vinto al massimo in una scommessa?", "Quanti euro hai perso al massimo in una scommessa?", "n", 1, "+"],
["Quanti minuti stai sotto la doccia?", "Quanti minuti ci metti a mangiare a pranzo?", "n", 1],
["Quanti cuscini ci sono sul tuo divano?", "Quante coperte hai sul letto d'inverno?", "n", 1],
["Quanti giorni riesci a stare senza vedere nessuno?", "Quanti giorni riesci a stare senza mangiare dolci?", "n", 2],
["Quante volte hai cantato al karaoke?", "Quante volte sei salito su un palco?", "n", 1],
["Quanti anni aveva la persona più anziana della tua famiglia che hai conosciuto?", "Quanti anni aveva il tuo insegnante preferito?", "n", 3],
["Quante volte hai sognato di volare?", "Quante volte hai sognato di cadere nel vuoto?", "n", 1],
["Quante ore resisti senza mangiare prima di diventare intrattabile?", "Quante ore di sonno ti servono per essere di buon umore?", "n", 1],
["Quanti colloqui di lavoro hai fatto?", "Quanti esami orali hai fatto in vita tua?", "n", 3],
["Quante volte al giorno apri il frigo senza prendere niente?", "Quante volte al giorno ti guardi allo specchio?", "n", 1],
["Quante volte hai rotto qualcosa a casa di altri?", "Quante volte hai dormito da amici quest'anno?", "n", 2],
["Quante volte sei caduto per strada da adulto?", "Quante volte hai sbattuto contro una porta a vetri?", "n", 1],
["Quante volte hai litigato con qualcuno in pubblico?", "Quante volte hai litigato con un vicino di casa?", "n", 1],
["Quante volte ti hanno scambiato per qualcun altro?", "Quante volte hai salutato qualcuno che non stava salutando te?", "n", 1],
["Quante persone conosciute su internet hai poi visto dal vivo?", "Quanti primi appuntamenti hai avuto nell'ultimo anno?", "n", 2, "+"],
["Quante volte hai scritto a un ex dopo mezzanotte?", "Quante volte hai riletto una vecchia chat con un ex?", "n", 1, "+"],
["Quante persone a questo tavolo hai visto ubriache?", "Quante persone a questo tavolo hai visto piangere?", "n", 1, "+"],
["Quante volte hai riso per finta a una battuta stasera?", "Quante volte hai guardato il telefono stasera?", "n", 2],
["A che età hai avuto il primo fidanzato o la prima fidanzata?", "A che età sei andato in discoteca la prima volta?", "n", 1, "+"],
["Quante volte hai rimandato la sveglia stamattina?", "Quante volte ti sei lamentato del lavoro o dello studio oggi?", "n", 1],
["Quante volte ti sei tagliato i capelli da solo?", "Quante volte hai provato a fare una dieta?", "n", 2],
["Quanti euro spendi per una pizza con bibita?", "Quanti euro lasci di mancia in un posto dove ti sei trovato bene?", "n", 3],
["Quante volte sei stato fuori dall'Europa?", "Quante volte hai preso una nave o un traghetto?", "n", 1],
["Quanti mesi al massimo sei stato senza vedere il tuo migliore amico?", "Quanti mesi al massimo sei stato senza tornare a casa dei tuoi?", "n", 1],
["Quanti anni avevi quando hai preso la patente?", "Quanti anni avevi quando hai avuto il primo lavoretto pagato?", "n", 1],
["Quanti scatoloni ti servirebbero per traslocare domani?", "Quanti sacchi della spazzatura riempiresti buttando le cose inutili di casa?", "n", 1],
["Quante volte hai ricevuto un regalo che hai poi riciclato?", "Quante volte hai fatto un regalo comprato all'ultimo minuto?", "n", 1],
["Quanti euro vorresti guadagnare al mese per essere felice?", "Quanti euro spendi in un anno per le vacanze?", "n", 3],
["Quanti biglietti della lotteria o gratta e vinci hai comprato in vita tua?", "Quante volte hai giocato a carte con soldi veri?", "n", 2, "+"],

// ---------------------------------------------------------------- PERCENTUALI
["In percentuale, quanto sei una persona puntuale?", "In percentuale, quanto sei una persona ordinata?", "%", 1],
["In percentuale, quanto sei soddisfatto della tua vita adesso?", "In percentuale, quanto è carica la batteria del tuo telefono adesso?", "%", 3],
["In percentuale, quanto credi all'oroscopo?", "In percentuale, quanto credi ai fantasmi?", "%", 1],
["In percentuale, quanto sei competitivo quando giochi?", "In percentuale, quanto ti arrabbi quando perdi?", "%", 1],
["In percentuale, quanto ti piace ballare?", "In percentuale, quanto ti piace cantare al karaoke?", "%", 1],
["In percentuale, quanto sei sicuro di aver scelto (o che sceglierai) la persona giusta?", "In percentuale, quanto ti fidi delle previsioni del meteo?", "%", 3],
["In percentuale, quanto sei mammone?", "In percentuale, quanto sei geloso?", "%", 2],
["In percentuale, quanto ti fidi dei tuoi amici con un segreto?", "In percentuale, quanto ti fidi del navigatore in una città che non conosci?", "%", 2],
["In percentuale, quanto ti piace il tuo lavoro o quello che studi?", "In percentuale, quanto ti piace la città in cui vivi?", "%", 1],
["In percentuale, quanto te la cavi in cucina?", "In percentuale, quanto te la cavi alla guida?", "%", 1],
["In percentuale, quanto sei sportivo?", "In percentuale, quanto sei pigro la domenica?", "%", 2],
["In percentuale, quanto sei romantico?", "In percentuale, quanto sei permaloso?", "%", 2],
["In percentuale, quanto ti fa paura il buio?", "In percentuale, quanto ti fanno paura i ragni?", "%", 1],
["In percentuale, quanto sei nostalgico?", "In percentuale, quanto sei ottimista sul futuro?", "%", 2],
["In percentuale, quanto ti consideri intelligente?", "In percentuale, quanto ti consideri attraente?", "%", 1],
["In percentuale, quanto sei sincero con le persone a cui vuoi bene?", "In percentuale, quanto sei sincero quando compili un questionario?", "%", 2],
["In percentuale, quanto ti piace la pizza con l'ananas?", "In percentuale, quanto ti piacciono i reality show?", "%", 2],
["In percentuale, quanto credi che esistano gli alieni?", "In percentuale, quanto credi che l'uomo sia andato davvero sulla Luna?", "%", 3],
["In percentuale, quanto ti stai annoiando in questo momento?", "In percentuale, quanta fame hai in questo momento?", "%", 1],
["Che percentuale dei tuoi soldi spendi in cibo?", "Che percentuale del tuo tempo libero passi con gli amici?", "%", 2],
["In percentuale, quanto ti senti adulto?", "In percentuale, quanto ti senti realizzato?", "%", 1],
["In percentuale, quanto sei bravo a mentire?", "In percentuale, quanto sei bravo a capire quando qualcuno mente?", "%", 1],
["In percentuale, quanto è disordinata la tua camera adesso?", "In percentuale, quanto è pieno il tuo frigorifero adesso?", "%", 2],
["In percentuale, quanto ti fidi dei politici?", "In percentuale, quanto sei informato su quello che succede nel mondo?", "%", 3],
["In percentuale, quanto sei un tipo da mare invece che da montagna?", "In percentuale, quanto sei un tipo da gatti invece che da cani?", "%", 1],
["In percentuale, quanto sei mattiniero?", "In percentuale, quanto sei nottambulo?", "%", 3],
["In percentuale, quanto ti piace il tuo nome?", "In percentuale, quanto ti piace la tua voce registrata?", "%", 2],
["In percentuale, quanto sei sicuro di passare l'esame di guida se lo rifacessi domani?", "In percentuale, quanto sei sicuro di sopravvivere una settimana su un'isola deserta?", "%", 2],
["Che percentuale dei tuoi amici conosci da più di dieci anni?", "Che percentuale dei tuoi contatti WhatsApp non senti da più di un anno?", "%", 1],
["In percentuale, quanto ti fidi di chi ti taglia i capelli?", "In percentuale, quanto ti fidi del tuo medico?", "%", 2],
["In percentuale, quanto ti sta divertendo questo gioco?", "In percentuale, quanto pensi di vincere questa partita?", "%", 2],
["In percentuale, quanto sei tirchio?", "In percentuale, quanto sei spendaccione?", "%", 3],
["In percentuale, quanto ti consideri un buon amico?", "In percentuale, quanto ti consideri bravo ad ascoltare?", "%", 1],
["In percentuale, quanto ti fa schifo il sushi?", "In percentuale, quanto ti piace il sushi?", "%", 3],
["In percentuale, quanto sei timido con gli sconosciuti?", "In percentuale, quanto sei espansivo alle feste?", "%", 3],
["In percentuale, quanto sei contento di come sono andati gli ultimi dodici mesi?", "In percentuale, quanto ti senti in forma adesso?", "%", 1],
["In percentuale, quanto ti piace fare regali?", "In percentuale, quanto ti piace riceverli?", "%", 1],
["In percentuale, quanto sei ansioso?", "In percentuale, quanto riesci a rilassarti in vacanza?", "%", 3],
["In percentuale, quanto sei bravo a ricordare i nomi?", "In percentuale, quanto sei bravo a ricordare i compleanni?", "%", 1],
["In percentuale, quanto credi al destino?", "In percentuale, quanto credi alla fortuna?", "%", 1],
["In percentuale, quanto ti piace il Natale?", "In percentuale, quanto ti piace il tuo compleanno?", "%", 1],
["In percentuale, quanta voglia hai di andare a lavorare o studiare lunedì?", "In percentuale, quanta voglia hai di fare sport domani?", "%", 1],
["In percentuale, quanto ti fideresti a lasciare il telefono sbloccato a questo tavolo?", "In percentuale, quanto ti fideresti a lasciare le chiavi di casa a questo tavolo?", "%", 1],
["In percentuale, quanto sei tecnologico?", "In percentuale, quanto te la cavi col fai-da-te?", "%", 2],
["In percentuale, quanto sei goloso?", "In percentuale, quanto mangi sano?", "%", 3],
["In percentuale, quanto sei ambizioso?", "In percentuale, quanto sei testardo?", "%", 1],
["In percentuale, quanto ti piacerebbe essere famoso?", "In percentuale, quanto ti piacerebbe vivere all'estero?", "%", 2],
["In percentuale, quanto sei soddisfatto del tuo ultimo taglio di capelli?", "In percentuale, quanto sei soddisfatto dell'ultima cosa che hai comprato?", "%", 1],
["In percentuale, quanto sei rancoroso?", "In percentuale, quanto sei vendicativo?", "%", 1],
["In percentuale, quanto ti vergogni della tua cronologia internet?", "In percentuale, quanto ti vergogneresti se leggessimo le tue chat?", "%", 1, "+"],
["In percentuale, quanto pianifichi le cose?", "In percentuale, quanto improvvisi nella vita?", "%", 3],
["In percentuale, quanto ti senti sottovalutato?", "In percentuale, quanto ti senti sopravvalutato?", "%", 3],
["In percentuale, quanto sai perdere con eleganza?", "In percentuale, quanto sai vincere senza vantarti?", "%", 1],
["In percentuale, quanto ti fidi dei tuoi ricordi d'infanzia?", "In percentuale, quanto ti ricordi del sogno di stanotte?", "%", 3],
["In percentuale, quanto sei curioso?", "In percentuale, quanto sei pettegolo?", "%", 1],
["In percentuale, quanto sei rimasto uguale a com'eri a quindici anni?", "In percentuale, quanto sei cambiato da quando avevi quindici anni?", "%", 3],
["In percentuale, quanto sei contento di quello che hai studiato?", "In percentuale, quanto rifaresti tutto uguale nella vita?", "%", 1],
["In percentuale, quanto è probabile che stanotte tu vada a letto prima dell'una?", "In percentuale, quanto è probabile che domattina ti svegli alla prima sveglia?", "%", 2],
["In percentuale, quanto credi che le persone siano buone?", "In percentuale, quanto credi di essere una brava persona?", "%", 2],
["In percentuale, quanto sei bravo a fare pace dopo un litigio?", "In percentuale, quanto chiedi scusa quando hai torto?", "%", 1],
["In percentuale, quanto hai capito le regole di questo gioco?", "In percentuale, quanto sei sicuro di non essere l'impostore adesso?", "%", 1],
["In percentuale, quanto sei sicuro che l'impostore stasera verrà scoperto?", "In percentuale, quanto ti fidi delle persone a questo tavolo?", "%", 2],
["In percentuale, quanto ti ricordi della tua prima cotta?", "In percentuale, quanto ti ricordi del tuo primo giorno di scuola?", "%", 1],
["In percentuale, quanto sei fedele alla tua squadra del cuore?", "In percentuale, quanto sei fedele al tuo parrucchiere o barbiere?", "%", 2],
["Che percentuale delle cose che compri online restituisci?", "Che percentuale dei vestiti che hai nell'armadio metti davvero?", "%", 3],
["In percentuale, quanto sei stressato questa settimana?", "In percentuale, quanto hai dormito bene questa settimana?", "%", 3],

// ---------------------------------------------------------------- DA 1 A 10
["Da 1 a 10, quanto sei stanco adesso?", "Da 1 a 10, quanta voglia hai di ballare adesso?", "10", 3],
["Da 1 a 10, quanto ti piacciono i bambini?", "Da 1 a 10, quanto ti piacciono i cani?", "10", 2],
["Da 1 a 10, quanto reggi il piccante?", "Da 1 a 10, quanto reggi il freddo?", "10", 1],
["Da 1 a 10, quanto è brutta la tua calligrafia?", "Da 1 a 10, quanto sei stonato quando canti?", "10", 1],
["Da 1 a 10, quanto te la cavi a nuotare?", "Da 1 a 10, quanto te la cavi a sciare?", "10", 2],
["Da 1 a 10, quanto sei drammatico quando stai male?", "Da 1 a 10, quanto esageri quando racconti una storia?", "10", 1],
["Da 1 a 10, quanto te la cavi a fare le valigie?", "Da 1 a 10, quanto te la cavi a montare i mobili?", "10", 1],
["Da 1 a 10, quanto è stata bella la tua ultima vacanza?", "Da 1 a 10, quanto è stato bello il tuo ultimo compleanno?", "10", 1],
["Da 1 a 10, quanto ti manca la scuola?", "Da 1 a 10, quanto ti piaceva la scuola?", "10", 1],
["Da 1 a 10, quanto te la cavi a flirtare?", "Da 1 a 10, quanto te la cavi a consolare qualcuno?", "10", 2, "+"],
["Da 1 a 10, quanto ti piace l'odore della benzina?", "Da 1 a 10, quanto ti piace l'odore del caffè?", "10", 3],
["Da 1 a 10, quanto sei superstizioso?", "Da 1 a 10, quanto sei religioso?", "10", 2],
["Da 1 a 10, quanto sarebbe dura per te vivere senza musica?", "Da 1 a 10, quanto sarebbe dura per te vivere senza caffè?", "10", 1],
["Da 1 a 10, quanta paura hai di volare?", "Da 1 a 10, quanta paura hai del dentista?", "10", 1],
["Da 1 a 10, quanto è disordinata la tua scrivania?", "Da 1 a 10, quanto è disordinata la galleria del tuo telefono?", "10", 1],
["Da 1 a 10, quanto te la cavi a disegnare?", "Da 1 a 10, quanto te la cavi a fare foto?", "10", 2],
["Da 1 a 10, quanto ti è piaciuta la cena di stasera?", "Da 1 a 10, quanto è comoda la sedia su cui sei seduto?", "10", 2],
["Da 1 a 10, quanto sai tenere un segreto?", "Da 1 a 10, quanto sai organizzare una sorpresa?", "10", 1],
["Da 1 a 10, quanto ti piace il calcio?", "Da 1 a 10, quanto ti piace la Formula 1?", "10", 1],
["Da 1 a 10, quanta ansia hai prima di un esame o di un colloquio?", "Da 1 a 10, quanta ansia hai prima di un volo?", "10", 1],
["Da 1 a 10, quanto te la cavi a parlare in pubblico?", "Da 1 a 10, quanto te la cavi a fare battute?", "10", 1],
["Da 1 a 10, quanto sei goloso di dolci?", "Da 1 a 10, quanto ti piace il formaggio?", "10", 1],
["Da 1 a 10, quanto sei pignolo?", "Da 1 a 10, quanto sei attento ai soldi?", "10", 1],
["Da 1 a 10, quanto te la cavi a orientarti senza navigatore?", "Da 1 a 10, quanto te la cavi a parcheggiare?", "10", 1],
["Da 1 a 10, quanto sei bravo a stare da solo?", "Da 1 a 10, quanto sei bravo a stare in mezzo alla gente?", "10", 3],
["Da 1 a 10, quanto ti piace la tua città?", "Da 1 a 10, quanto ti piace il tuo quartiere?", "10", 1],
["Da 1 a 10, quanto sei un tipo da abbracci?", "Da 1 a 10, quanto sei un tipo da pacche sulle spalle?", "10", 2],
["Da 1 a 10, quanto sei pronto a un'apocalisse zombie?", "Da 1 a 10, quanto sei pronto a un trasloco domani?", "10", 1],

// ---------------------------------------------------------------- SU UN GIOCATORE
["Secondo te, quante volte {G} è arrivato in ritardo quest'anno?", "Secondo te, quante volte {G} ha dato buca quest'anno?", "n", 1],
["In percentuale, quanto {G} sarebbe un buon genitore?", "In percentuale, quanto {G} sarebbe un buon capo?", "%", 1],
["In percentuale, quanto {G} sopravviverebbe a un'apocalisse zombie?", "In percentuale, quanto {G} sopravviverebbe una settimana senza telefono?", "%", 2],
["Da 1 a 10, quanto cucina bene {G}?", "Da 1 a 10, quanto balla bene {G}?", "10", 1],
["Secondo te, quanti euro spenderebbe {G} per una cena?", "Secondo te, quanti euro spenderebbe {G} per un paio di scarpe?", "n", 1],
["In percentuale, quanto {G} sa tenere un segreto?", "In percentuale, quanto {G} sa dire una bugia senza ridere?", "%", 2],
["In percentuale, quanto è puntuale {G}?", "In percentuale, quanto è ordinata la casa di {G}?", "%", 1],
["Da 1 a 10, quanto andrebbe bene {G} a un quiz in tv?", "Da 1 a 10, quanto andrebbe bene {G} in un reality?", "10", 2],
["In percentuale, quanto ti fideresti di {G} alla guida?", "In percentuale, quanto ti fideresti a lasciare il tuo animale a {G} per una settimana?", "%", 1],
["Secondo te, quanti caffè beve {G} in un giorno?", "Secondo te, quante ore dorme {G} a notte?", "n", 1],
["Secondo te, quanti minuti ci mette {G} a prepararsi per uscire?", "Secondo te, quanti minuti ci mette {G} a rispondere a un messaggio?", "n", 2],
["In percentuale, quanto è competitivo {G} in questo gioco?", "In percentuale, quanto sta mentendo {G} stasera?", "%", 1],
["Da 1 a 10, quanto romanticismo c'è in {G}?", "Da 1 a 10, quanta pazienza c'è in {G}?", "10", 1],
["Secondo te, fino a che età vivrà {G}?", "Secondo te, a che età andrà in pensione {G}?", "n", 3],
["In percentuale, quanto è probabile che {G} finisca in tv un giorno?", "In percentuale, quanto è probabile che {G} vada a vivere all'estero?", "%", 2],
["Secondo te, quante volte ha pianto {G} quest'anno?", "Secondo te, quante volte ha perso la pazienza {G} quest'anno?", "n", 1],
["Secondo te, quanti amici veri ha {G}?", "Secondo te, quanti ex ha {G}?", "n", 2, "+"],
["Da 1 a 10, quanto è disordinata la camera di {G}?", "Da 1 a 10, quanto è disordinato il telefono di {G}?", "10", 1],
["In percentuale, quanto è probabile che {G} vinca questa partita?", "In percentuale, quanto è probabile che {G} sia l'impostore in questo round?", "%", 3],
["Secondo te, per quanti euro {G} mangerebbe un insetto?", "Secondo te, per quanti euro {G} si tingerebbe i capelli di verde?", "n", 1],
["Secondo te, quante volte al mese {G} va in palestra?", "Secondo te, quante volte al mese {G} ordina cibo a domicilio?", "n", 1],
["In percentuale, quanto è un tipo da festa {G}?", "In percentuale, quanto è un tipo da divano {G}?", "%", 3],
["Da 1 a 10, quanto si arrabbia {G} quando perde?", "Da 1 a 10, quanto si vanta {G} quando vince?", "10", 1],
["Secondo te, quante ore passa {G} al telefono in un giorno?", "Secondo te, quante ore passa {G} a lavorare o studiare in un giorno?", "n", 2],
["In percentuale, quanto è probabile che {G} arrivi puntuale al prossimo appuntamento?", "In percentuale, quanto è probabile che {G} si ricordi il tuo compleanno?", "%", 1],
["Secondo te, quanti figli avrà {G}?", "Secondo te, quanti cani avrà {G} nella vita?", "n", 1],
["Da 1 a 10, quanto regge il piccante {G}?", "Da 1 a 10, quanto regge l'alcol {G}?", "10", 1, "+"],
["In percentuale, quanto ti fideresti di {G} con un segreto?", "In percentuale, quanto ti fideresti di {G} con un prestito?", "%", 1],
["Secondo te, quanti selfie ha {G} nel telefono?", "Secondo te, quante foto di cibo ha {G} nel telefono?", "n", 1],
["In percentuale, quanto è probabile che {G} si sposi entro cinque anni?", "In percentuale, quanto è probabile che {G} cambi città entro cinque anni?", "%", 2],
["Secondo te, quanti minuti resiste {G} senza guardare il telefono?", "Secondo te, quanti minuti ci mette {G} ad addormentarsi?", "n", 2],
["Da 1 a 10, quanto è testardo {G}?", "Da 1 a 10, quanto è permaloso {G}?", "10", 1],
["In percentuale, quanto vorresti {G} come testimone di nozze?", "In percentuale, quanto ti porteresti {G} in viaggio per un mese?", "%", 1],
["Secondo te, quante volte {G} ha cambiato idea stasera?", "Secondo te, quante volte {G} ha riso stasera?", "n", 3],
["Da 1 a 10, quanto sopravviverebbe {G} su un'isola deserta?", "Da 1 a 10, quanto sopravviverebbe {G} a una settimana con i tuoi parenti?", "10", 1],
["In percentuale, quanto somiglia {G} a sua madre?", "In percentuale, quanto somiglia {G} a suo padre?", "%", 1],
["Secondo te, quante paia di scarpe ha {G}?", "Secondo te, quanti euro ha {G} nel portafoglio adesso?", "n", 2],
["Da 1 a 10, quanto sarebbe bravo {G} a fare il politico?", "Da 1 a 10, quanto sarebbe bravo {G} a fare il prete?", "10", 3],
];
